# Generated by Django 3.2.9 on 2021-11-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brief_description', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=32)),
                ('lga', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('duration', models.IntegerField(default=1)),
                ('detail_description', models.TextField()),
                ('cost', models.FloatField()),
                ('cost_breakdown', models.TextField()),
                ('expiration', models.IntegerField(blank=True)),
                ('investigated', models.BooleanField(default=False)),
                ('investigation_note', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('closed_note', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=128)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('backers', models.ManyToManyField(blank=True, related_name='backers', to=settings.AUTH_USER_MODEL)),
                ('closer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closer', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigator', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(related_name='volunteers', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cause_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Infrastructure', 'Infrastructure'), ('Health', 'Health')], max_length=64, null=True)),
                ('slug', models.SlugField(choices=[('infrastructure', 'infrastructure'), ('health', 'health')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True)),
                ('title', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=32)),
                ('lga', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('occupation', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(upload_to='main/users/profile-pics/')),
                ('amount_contributed', models.FloatField(default=0.0)),
                ('amount_owed', models.FloatField(default=0.0)),
                ('monthly_payment', models.BooleanField(default=False)),
                ('monthly_vote', models.BooleanField(default=False)),
                ('rank', models.CharField(blank=True, max_length=32)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cause_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to=main.models.cause_directory_path)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cause')),
            ],
        ),
    ]
