# Generated by Django 3.2.9 on 2021-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Awaiting approval', 'Awaiting approval'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], max_length=32, null=True),
        ),
    ]
