# Generated by Django 3.2.9 on 2021-12-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211130_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cause_file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Images', 'Images'), ('Documents', 'Documents'), ('Videos', 'Videos')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cause_file',
            name='usage',
            field=models.CharField(blank=True, choices=[('Investigation Files', 'Investigation Files'), ('Ongoing Report', 'Ongoing Report'), ('Profile Picture', 'Profile Picture'), ('Proof of Completion', 'Proof of Completion'), ('Proof of Payment', 'Proof of Payment'), ('Proof of Existence', 'Proof of Existence')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='main/users/profile-pics'),
        ),
    ]
