# Generated by Django 3.2.9 on 2021-11-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cause_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cause_category',
            new_name='Cause_categorie',
        ),
        migrations.RenameModel(
            old_name='Cause_files',
            new_name='Cause_file',
        ),
    ]
