# Generated by Django 3.2.9 on 2021-12-04 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211204_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='investigation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cause',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to=settings.AUTH_USER_MODEL),
        ),
    ]
