# Generated by Django 3.2.9 on 2021-11-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211121_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
