# Generated by Django 3.2.9 on 2021-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cause_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
