# Generated by Django 3.2.9 on 2021-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cause_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='status',
            field=models.CharField(default='Awaiting approval', max_length=32),
            preserve_default=False,
        ),
    ]
