# Generated by Django 3.2.9 on 2021-11-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
