# Generated by Django 3.2.9 on 2021-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cause_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause_file',
            old_name='upload',
            new_name='file_upload',
        ),
        migrations.RemoveField(
            model_name='cause_file',
            name='usage',
        ),
        migrations.AddField(
            model_name='cause_file',
            name='purpose',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cause_file',
            name='file_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
