# Generated by Django 3.2.9 on 2021-11-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cause_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
