# Generated by Django 3.2.9 on 2021-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cause_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
