# Generated by Django 3.2.9 on 2021-12-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211206_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cause_categorie',
        ),
        migrations.AddField(
            model_name='cause',
            name='category',
            field=models.CharField(default='Health', max_length=32),
            preserve_default=False,
        ),
    ]
