# Generated by Django 3.2.9 on 2021-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211130_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pic',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
