# Generated by Django 3.2.9 on 2021-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='month',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='account_total',
            field=models.IntegerField(default=0.0),
        ),
    ]
