# Generated by Django 3.2.9 on 2021-12-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211215_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='account_total',
            new_name='total_amount',
        ),
    ]
