# Generated by Django 3.2.9 on 2021-12-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_account_total_info_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='month',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='year',
            field=models.FloatField(),
        ),
    ]
