# Generated by Django 3.2.9 on 2021-12-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211215_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='monthly_payment',
            new_name='monthly_donation',
        ),
    ]
