# Generated by Django 3.2.9 on 2021-12-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_monthly_payment_user_monthly_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='amount_contributed',
            new_name='total_contribution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='amount_owed',
        ),
    ]
